import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import { Box } from "@chakra-ui/react";

import Cards from "../components/Cards";

export default function Home() {
  return (
    <Box margin="50px 50px">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Cards />
    </Box>
  );
}
